name: colorless-scotty
version: '0.0.1'
category: Web
synopsis: Scotty server add-on for Colorless
description: Scotty server add-on for Colorless
maintainer: Joe Vargas
license: BSD3
extra-source-files:
- package.yaml
- README.md
ghc-options: -Wall
default-extensions:
- OverloadedStrings
- NamedFieldPuns
library:
  dependencies:
  - aeson
  - base >= 4.7 && < 5
  - colorless
  - scotty
  - text
  - mtl
  - wai
  source-dirs: library
