name: colorless
version: '2.2.10'
category: Web
synopsis: Colorless
description: Colorless
maintainer: Joe Vargas
license: BSD3
extra-source-files:
- package.yaml
- README.md
ghc-options: -Wall
default-extensions:
- ConstraintKinds
- DeriveGeneric
- DuplicateRecordFields
- FlexibleContexts
- FlexibleInstances
- GADTs
- GeneralizedNewtypeDeriving
- KindSignatures
- LambdaCase
- MultiParamTypeClasses
- NamedFieldPuns
- OverloadedStrings
- RankNTypes
- ScopedTypeVariables
- TupleSections
- TypeApplications
- TypeOperators
library:
  dependencies:
  - aeson
  - base >= 4.7 && < 5
  - bytestring
  - containers
  - errors
  - exceptions
  - lifted-async
  - monad-control
  - monad-logger
  - mtl
  - random
  - scientific
  - text
  - text-conversions
  - unordered-containers
  - vector
  source-dirs: library
tests:
  colorless-suite:
    dependencies:
    - aeson
    - base >= 4.7 && < 5
    - colorless
    - containers
    - hspec
    - scientific
    - text
    - tuple
    - vector
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Spec.hs
    source-dirs: tests
